name: update

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Run FastAPI server
      run: |
        pip install -r requirements.txt
        uvicorn main:app --host 0.0.0.0 --port 8000 & sleep 3

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1
      id: setup-chrome
      with:
        chrome-version: 'stable'
    
    - name: Set up Edge
      uses: browser-actions/setup-edge@v1
      id: setup-edge
      with:
        edge-version: 'stable'
    
    - name: Set up Firefox
      uses: browser-actions/setup-firefox@v1
      id: setup-firefox
      with:
        firefox-version: 'latest'

    - name: Set up Xvfb
      run: |
        sudo apt-get install -y xvfb

    - name: Run Chrome
      run: |
        xvfb-run ${{ steps.setup-chrome.outputs.chrome-path }} http://127.0.0.1:8000/chrome --timeout=3000
    
    - name: Run Edge
      run: |
        xvfb-run ${{ steps.setup-edge.outputs.edge-path }} http://127.0.0.1:8000/edge --timeout=3000

    - name: Run Firefox
      run: |
        xvfb-run ${{ steps.setup-firefox.outputs.firefox-path }} http://127.0.0.1:8000/firefox --timeout=3000

    - name: Run Headless Chrome
      run: |
        ${{ steps.setup-chrome.outputs.chrome-path }} http://127.0.0.1:8000/headless-chrome --headless --timeout=3000

    - name: Run Headless Edge
      run: |
        ${{ steps.setup-edge.outputs.edge-path }} http://127.0.0.1:8000/headless-edge --headless --timeout=3000

    - name: Run Headless Firefox
      run: |
        ${{ steps.setup-firefox.outputs.firefox-path }} http://127.0.0.1:8000/headless-firefox --headless & sleep 3
    

    - name: Commit
      continue-on-error: true
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Action"
        git add .
        git commit -m "Update"
        git push origin main
