name: FastAPI Test Workflow

on:
  schedule:
    - cron: '0 21 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1
      id: setup-chrome
      with:
        chrome-version: 'stables'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run FastAPI server
      run: |
        uvicorn main:app --host 0.0.0.0 --port 8000 & sleep 3
        ${{ steps.setup-chrome.outputs.chrome-path }}  http://127.0.0.1:8000/chromium-browser --headress  --timeout=1000

    - name: Commit
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add .
        git commit -m "Update"
        git push
