name: FastAPI Test Workflow

on:
  schedule:
    - cron: '0 21 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run FastAPI server
      run: |
        uvicorn main:app --host 0.0.0.0 --port 8000 & sleep 3
    
    - name: Chromium
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        chromium-browser  http://127.0.0.1:8000/chromium-browser --headress  --timeout=1000

